### ISSUE TITLE
Add C++ basic programs

### ISSUE THREAD

**Issue by tamit4119** [tamit4119/Cpp-Basics#2]

**Comment by Divjyo15** [comment]
can you assign me

**Comment by amanaggarwal06** [comment]
Hey, I want to work on this.
Can you please assign it to me @tamit4119?

**Comment by HarshitRawat11** [comment]
Hi @tamit4119.
Please assign this issue to me.

**Comment by Vaishnavi-More** [comment]
Hey @tamit4119 Please  assign this issue to me.

**Comment by ankitkumar0622** [comment]
Hi , can you assign this task to me.

**Comment by Vaishnavi-More** [comment]
Hey @tamit4119 I have requested pull request kindly review and accept it!
Thank you!

**Comment by leslievelderrainx** [comment]
Hi @tamit4119, can I be assigned to this task too?

**Comment by ujwxl23** [comment]
Hello @tamit4119, Could you assign this task to me?

**Comment by ManasiGDeshmukh** [comment]
Manasi Deshmukh
Cummins College of Engineering for Women, Pune
SY Computer Department
can you assign this issue to me?
